import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, it } from "node:test";
import { QuirtError } from "./error.js";
import type { QuirtConfig } from "./config.js";
import { QuirtJobManager } from "./job-manager.js";
import type { QuirtPtyExit, QuirtPtyFactory, QuirtPtyProcess, QuirtPtySpawn } from "./pty.js";
import { QuirtRecordingService } from "./recording-service.js";
import { QuirtSessionManager } from "./session-manager.js";
import { QuirtSessionNativeService } from "./session-native-service.js";
import { QuirtStateStore } from "./state.js";
import { quirtTestConfig } from "./test-support.test.js";
import type { QuirtTmuxController } from "./tmux.js";

class FakePty implements QuirtPtyProcess {
  readonly events = new EventEmitter(); readonly writes: Buffer[] = []; columns = 80; rows = 24; lastSignal: NodeJS.Signals | null = null;
  constructor(readonly pid: number) {} write(bytes: Buffer): void { this.writes.push(Buffer.from(bytes)); } resize(columns: number, rows: number): void { this.columns = columns; this.rows = rows; } signal(signal: NodeJS.Signals): void { this.lastSignal = signal; if (signal === "SIGKILL" || signal === "SIGHUP") this.events.emit("exit", { exitCode: 128, signal: 1 } satisfies QuirtPtyExit); } pause(): void {} resume(): void {}
  onData(listener: (bytes: Buffer) => void): () => void { this.events.on("data", listener); return () => this.events.off("data", listener); } onExit(listener: (exit: QuirtPtyExit) => void): () => void { this.events.on("exit", listener); return () => this.events.off("exit", listener); } output(bytes: Buffer): void { this.events.emit("data", Buffer.from(bytes)); }
}
class FakePtys implements QuirtPtyFactory { readonly processes: FakePty[] = []; spawn(_input: QuirtPtySpawn): QuirtPtyProcess { const value = new FakePty(9000 + this.processes.length); this.processes.push(value); return value; } }
class NoTmux { async version(): Promise<string> { return "tmux-test"; } async hasSession(): Promise<boolean> { return false; } attach(): never { throw new Error("not used"); } async resize(): Promise<void> {} async signal(): Promise<void> {} async killSession(): Promise<void> {} }

const roots: string[] = []; const stores: QuirtStateStore[] = []; const managers: QuirtSessionManager[] = []; const jobs: QuirtJobManager[] = []; const recordings: QuirtRecordingService[] = []; const owner = "a".repeat(64);
afterEach(() => { for (const service of recordings.splice(0)) service.shutdown(); for (const manager of managers.splice(0)) manager.shutdown(); for (const manager of jobs.splice(0)) manager.shutdown(); for (const store of stores.splice(0)) try { store.close(); } catch {} for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }); });
async function fixture(options: { database?: boolean; now?: () => Date } = {}) { const root = mkdtempSync(join(tmpdir(), "quirt-recording-")); roots.push(root); const config = quirtTestConfig(root); const state = new QuirtStateStore(options.database ? config.databasePath : ":memory:", { now: options.now }); stores.push(state); const ptys = new FakePtys(); const sessions = new QuirtSessionManager(config, state, ptys, new NoTmux() as unknown as QuirtTmuxController); managers.push(sessions); const jobManager = new QuirtJobManager(config, state, ptys); jobs.push(jobManager); const recording = new QuirtRecordingService(config, state, sessions); recordings.push(recording); const native = new QuirtSessionNativeService(config, state, sessions, jobManager, recording); const session = await sessions.open({ mode: "direct", executable: "/bin/bash", loginShell: false, columns: 10, rows: 3 }, owner); return { root, config, state, ptys, sessions, jobs: jobManager, recording, native, session }; }

describe("Quirt recordings and native session state", () => {
  it("records raw input/output, resize, signal, markers, and bookmarks with durable indexes", async () => {
    const f = await fixture(); const started = f.recording.start({ sessionId: f.session.sessionId, name: "operator" }, owner); const recordingId = started.recordingId as string;
    await f.sessions.write(f.session.sessionId, owner, Buffer.from([0, 255, 3])); f.ptys.processes[0]!.output(Buffer.from("hello \u001b[31mred\u001b[0m café\n")); await f.sessions.resize(f.session.sessionId, owner, 20, 5); await f.sessions.signal(f.session.sessionId, owner, "SIGUSR1"); f.recording.start({ recordingId, marker: "checkpoint", bookmark: "important" }, owner); const stopped = f.recording.stop({ recordingId }, owner); assert.equal((stopped.recording as { status: string }).status, "completed");
    const listed = f.recording.list(owner).recordings as Array<Record<string, unknown>>; assert.equal(listed.length, 1); assert.equal(listed[0]!.inputBytes, 3); assert.ok((listed[0]!.outputBytes as number) > 0); assert.deepEqual(listed[0]!.markers, ["recording-start", "checkpoint", "recording-stop"]); assert.deepEqual(listed[0]!.bookmarks, ["important"]);
    assert.equal(typeof listed[0]!.durationMilliseconds, "number"); const search = f.recording.search({ recordingId, query: "café" }, owner); const match = (search.matches as Array<{ rawOffsetExact: boolean; eventStreamOffset: number }>)[0]!; assert.equal(match.rawOffsetExact, false); assert.equal(typeof match.eventStreamOffset, "number"); const replay = f.recording.replay({ recordingId, maximumEvents: 100, speed: 2 }, owner); assert.ok(replay.binary.includes(Buffer.from([0, 255, 3]))); assert.equal(replay.payload.speed, 2); const events = replay.payload.events as Array<{ sequence: number; eventType: string; timestampNs: number }>; assert.ok(events.length >= 7); assert.deepEqual(events.map(event => event.sequence), events.map(event => event.sequence).sort((a, b) => a - b)); assert.ok(events.some(event => event.eventType === "terminal-resize")); assert.ok(events.every(event => typeof event.timestampNs === "number"));
  });

  it("exports deterministic raw, asciinema, and HTML pages and denies cross-principal access", async () => {
    const f = await fixture(); const recordingId = f.recording.start({ sessionId: f.session.sessionId }, owner).recordingId as string; f.ptys.processes[0]!.output(Buffer.from("export <safe>\n")); f.recording.stop({ recordingId }, owner);
    for (const format of ["quirt-json-v1", "asciinema-v2", "html-transcript"] as const) { const first = f.recording.export({ recordingId, format }, owner); const second = f.recording.export({ recordingId, format }, owner); assert.deepEqual(second.binary, first.binary); assert.equal(second.payload.sha256, first.payload.sha256); assert.equal(second.payload.eof, true); if (format === "quirt-json-v1") assert.match(first.binary.toString(), /quirt-recording-manifest/u); const page = f.recording.export({ recordingId, format, maximumBytes: Math.min(16, first.binary.length) }, owner); if (first.binary.length > 16) { assert.equal(page.payload.eof, false); const tail = f.recording.export({ recordingId, format, offset: page.payload.nextOffset as number, maximumBytes: 1024 * 1024 }, owner); assert.deepEqual(Buffer.concat([page.binary, tail.binary]), first.binary); } }
    assert.throws(() => f.recording.list("b".repeat(64)).recordings && f.recording.replay({ recordingId }, "b".repeat(64)), (error: unknown) => error instanceof QuirtError && error.code === "authorization_failed"); const active = f.recording.start({ sessionId: f.session.sessionId }, owner).recordingId as string; assert.throws(() => f.recording.stop({ recordingId: active, remove: true }, owner), (error: unknown) => error instanceof QuirtError && error.code === "conflict"); f.recording.stop({ recordingId: active }, owner); f.recording.stop({ recordingId: active, remove: true }, owner); f.recording.stop({ recordingId, remove: true }, owner); assert.equal((f.recording.list(owner).recordings as unknown[]).length, 0);
  });

  it("pages recording inventory with a stable opaque continuation token", async () => {
    const f = await fixture(); for (let index = 0; index < 3; index += 1) { const recordingId = f.recording.start({ sessionId: f.session.sessionId, name: `page-${index}` }, owner).recordingId as string; f.recording.stop({ recordingId }, owner); }
    const first = f.recording.list(owner, { maximumRecordings: 2 }); assert.equal((first.recordings as unknown[]).length, 2); assert.equal(first.truncated, true); assert.equal(typeof first.continuationToken, "string"); const second = f.recording.list(owner, { maximumRecordings: 2, continuationToken: first.continuationToken as string }); assert.equal((second.recordings as unknown[]).length, 1); assert.equal(second.truncated, false); assert.equal(second.continuationToken, null); assert.throws(() => f.recording.list(owner, { continuationToken: "not-json" }), (error: unknown) => error instanceof QuirtError && error.code === "invalid_request");
  });

  it("searches and renders retained terminal bytes with exact offsets, ANSI attributes, Unicode width, and loss truth", async () => {
    const f = await fixture(); f.ptys.processes[0]!.output(Buffer.from("abc\u001b[38;2;1;2;3m界\u001b[0m xyz\n\u001b[?1049h\u001b]8;;https://example.invalid\u0007ALT\u001b]8;;\u0007")); const search = f.native.search({ sessionId: f.session.sessionId, query: "xyz" }, owner); const match = (search.matches as Array<{ startOffset: number }>)[0]!; assert.equal(match.startOffset, Buffer.byteLength("abc\u001b[38;2;1;2;3m界\u001b[0m "));
    const rendered = f.native.render({ sessionId: f.session.sessionId, rows: 3, columns: 10 }, owner); const render = rendered.render as { alternateScreen: boolean; rows: string[]; cells: Array<Array<{ attributes: Record<string, unknown> }>>; cursor: { row: number; column: number }; lossIndicators: string[] }; assert.equal(render.alternateScreen, true); assert.equal(render.rows[0], "ALT"); assert.deepEqual(render.cursor, { row: 0, column: 3, visible: true }); assert.equal(render.cells[0]![0]!.attributes.hyperlink, "https://example.invalid"); assert.ok(render.lossIndicators.length === 0);
    f.ptys.processes[0]!.output(Buffer.from([0xff, 0x1b, 0x5f, 0x47, 0x61, 0x3d, 0x54, 0x1b, 0x5c])); const lossy = f.native.render({ sessionId: f.session.sessionId, rows: 3, columns: 10 }, owner).render as { lossIndicators: string[] }; assert.ok(lossy.lossIndicators.includes("invalid-or-incomplete-utf8")); assert.ok(lossy.lossIndicators.includes("kitty-image-not-rendered"));
  });

  it("creates principal-bound durable handoffs and resumes at the exact reader offset without a replacement shell", async () => {
    const f = await fixture(); f.ptys.processes[0]!.output(Buffer.from("0123456789")); const reader = await f.sessions.attach(f.session.sessionId, owner, { after: 4 }); const descriptive = f.native.snapshot({ sessionId: f.session.sessionId, createHandoff: false }, owner); assert.equal(descriptive.handoff, null); const snapshot = f.native.snapshot({ sessionId: f.session.sessionId, readerId: (reader.reader as { readerId: string }).readerId, createHandoff: true, clientMetadata: { client: "conversation-a", workspaceId: null } }, owner); const handoff = snapshot.handoff as { handoffId: string; readerOffset: number; sessionName: string; workingDirectory: string; environmentSummary: { valuesIncluded: boolean }; activePreviews: unknown[]; activeTunnels: unknown[]; unfinishedWork: unknown[] }; assert.equal(handoff.readerOffset, 4); assert.equal(handoff.sessionName, f.session.name); assert.equal(handoff.workingDirectory, f.session.workingDirectory); assert.equal(handoff.environmentSummary.valuesIncluded, false); assert.deepEqual(handoff.activePreviews, []); assert.deepEqual(handoff.activeTunnels, []); assert.deepEqual(handoff.unfinishedWork, []); const restored = f.native.handoff(handoff.handoffId, owner); assert.equal(restored.sessionId, f.session.sessionId); assert.equal(restored.after, 4); const processCount = f.ptys.processes.length; const attached = await f.sessions.attach(restored.sessionId, owner, { after: restored.after }); assert.equal((attached.session as { sessionId: string }).sessionId, f.session.sessionId); assert.equal(f.ptys.processes.length, processCount);
    assert.throws(() => f.native.handoff(handoff.handoffId, "b".repeat(64)), (error: unknown) => error instanceof QuirtError && error.code === "authorization_failed"); assert.throws(() => f.native.snapshot({ sessionId: f.session.sessionId, createHandoff: true, clientMetadata: { workspaceId: "workspace" } }, owner), (error: unknown) => error instanceof QuirtError && error.code === "authorization_failed");
    const wrongTarget = new QuirtSessionNativeService({ ...f.config, targetHost: "other-target" } as QuirtConfig, f.state, f.sessions, f.jobs, f.recording); assert.throws(() => wrongTarget.handoff(handoff.handoffId, owner), (error: unknown) => error instanceof QuirtError && error.code === "authorization_failed");
  });

  it("snapshots active jobs, transfers, recordings, repositories, and worktrees as descriptive reconnect state", async () => {
    const f = await fixture(); const job = f.state.createJob({ jobId: "job-snapshot", requestId: "request-snapshot", ownerPrincipalFingerprint: owner, command: { executable: "/bin/sleep", arguments: ["10"] }, workingDirectory: f.root }); f.state.updateJob(job.jobId, { status: "running", processId: 1234, started: true });
    f.state.native.createTransfer({ transferId: "transfer-snapshot", direction: "upload", status: "active", ownerPrincipalFingerprint: owner, sourcePath: null, destinationPath: join(f.root, "destination"), temporaryPath: join(f.root, "partial"), expectedSize: 10, chunkSize: 4, digestAlgorithm: "sha256", expectedDigest: null, compression: "none", archiveFormat: "none", metadata: {}, sourceIdentity: null });
    f.state.native.putObject("quirt_materializations", { objectId: "materialization-snapshot", ownerPrincipalFingerprint: owner, status: "ready", data: { destination: f.root, commit: "1".repeat(40), tree: "2".repeat(40), branch: "main" } }); f.state.native.putObject("quirt_worktrees", { objectId: "worktree-snapshot", ownerPrincipalFingerprint: owner, status: "ready", data: { destination: join(f.root, "worktree"), commit: "1".repeat(40), branch: "main" } }); const recordingId = f.recording.start({ sessionId: f.session.sessionId }, owner).recordingId as string;
    const result = f.native.snapshot({ sessionId: f.session.sessionId, createHandoff: false }, owner); const snapshot = result.snapshot as { checkpointType: string; processCheckpoint: boolean; activeJobs: unknown[]; activeTransfers: unknown[]; recordings: Array<{ recordingId: string }>; repositories: unknown[]; worktrees: unknown[]; terminal: { renderedState: { rows: string[] } }; environmentSummary: { valuesIncluded: boolean }; foregroundProcesses: unknown[] }; assert.equal(snapshot.checkpointType, "descriptive-reconnect-state"); assert.equal(snapshot.processCheckpoint, false); assert.equal(snapshot.activeJobs.length, 1); assert.equal(snapshot.activeTransfers.length, 1); assert.equal(snapshot.recordings[0]!.recordingId, recordingId); assert.equal(snapshot.repositories.length, 1); assert.equal(snapshot.worktrees.length, 1); assert.equal(snapshot.terminal.renderedState.rows.length, f.session.rows); assert.equal(snapshot.environmentSummary.valuesIncluded, false); assert.equal(snapshot.foregroundProcesses.length, 1);
  });

  it("rejects expired handoffs without converting them into reusable bearer authority", async () => {
    let now = new Date(); const f = await fixture({ now: () => now }); const result = f.native.snapshot({ sessionId: f.session.sessionId, createHandoff: true, expiresInSeconds: 60 }, owner); const handoff = result.handoff as { handoffId: string }; now = new Date("2100-01-01T00:00:00.000Z"); assert.throws(() => f.native.handoff(handoff.handoffId, owner), (error: unknown) => error instanceof QuirtError && error.code === "stale_request");
  });

  it("classifies active recordings across restart without inventing missing terminal bytes", async () => {
    const f = await fixture({ database: true }); const recordingId = f.recording.start({ sessionId: f.session.sessionId }, owner).recordingId as string; f.ptys.processes[0]!.output(Buffer.from("before-restart")); f.recording.shutdown(); recordings.splice(recordings.indexOf(f.recording), 1); f.sessions.shutdown(); managers.splice(managers.indexOf(f.sessions), 1); f.jobs.shutdown(); jobs.splice(jobs.indexOf(f.jobs), 1); f.state.close(); stores.splice(stores.indexOf(f.state), 1);
    const state = new QuirtStateStore(f.config.databasePath); stores.push(state); const ptys = new FakePtys(); const sessions = new QuirtSessionManager(f.config, state, ptys, new NoTmux() as unknown as QuirtTmuxController); managers.push(sessions); await sessions.recover(); const recording = new QuirtRecordingService(f.config, state, sessions); recordings.push(recording); const recovery = recording.recover(owner); assert.equal(recovery.interrupted, 1); const record = state.native.getObject("quirt_recordings", recordingId, owner); assert.equal(record.status, "interrupted"); assert.ok((record.data.lossIndicators as string[]).includes("session-unavailable-after-restart"));
  });

  it("resumes an active recording when its durable session remains attachable and records the restart gap", async () => {
    const f = await fixture(); const recordingId = f.recording.start({ sessionId: f.session.sessionId }, owner).recordingId as string; f.recording.shutdown(); recordings.splice(recordings.indexOf(f.recording), 1); const resumed = new QuirtRecordingService(f.config, f.state, f.sessions); recordings.push(resumed); const recovery = resumed.recover(owner); assert.deepEqual(recovery, { resumed: 1, interrupted: 0 }); const record = f.state.native.getObject("quirt_recordings", recordingId, owner); assert.equal(record.status, "active"); assert.ok((record.data.lossIndicators as string[]).includes("supervisor-restart-gap")); assert.ok(f.state.native.recordingEvents(recordingId, -1, 100).some(event => event.eventType === "recovery"));
  });
});
